openapi: 3.0.3
info:
  title: Salamin API
  description: 🪞 Professional brand analysis API for developers
  version: 1.0.0
  contact:
    name: API Support
    email: support@salamin.com

servers:
  - url: http://localhost:3605/v1
    description: Development server
  - url: https://api.salamin.com/v1
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: getHealth
      x-eov-operation-handler: system
      tags:
        - System
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    example: 201
                  message:
                    type: string
                    example: OK

components:
  schemas: {}
  securitySchemes: {}

tags:
  - name: System
    description: System operations
